# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_KOTLIN_MINIMAL)		+= kotlin_minimal.o
obj-$(CONFIG_SAMPLE_KOTLIN_PRINT)		+= kotlin_print.o
obj-$(CONFIG_SAMPLE_KOTLIN_PARAMETERS)		+= kotlin_parameters.o
obj-$(CONFIG_SAMPLE_KOTLIN_DRIVER_PLATFORM)	+= kotlin_driver_platform.o
obj-$(CONFIG_SAMPLE_KOTLIN_PCI_DRIVER)		+= kotlin_pci_driver.o
obj-$(CONFIG_SAMPLE_KOTLIN_USERSPACE)		+= userspace_init/
